version: "3.5"
networks:
    vue-app-dev-network:
        name: vue-app-dev-network
services:
    vue-app-dev:
        container_name: vue-app-dev
        image: node:latest
        volumes:
            - ./app:/app
        working_dir: /app
        ports:
            - "8080:8080"
        command: "bash -c 'yarn && yarn run dev-docker'"
        networks:
            - vue-app-dev-network
