version: "3.5"
networks:
    yggdrasil-frontend-network:
        name: yggdrasil-frontend-network
services:
    nginx:
        container_name: yggdrasil-frontend-nginx
        image: nginx:latest
        restart: always
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./app/dist:/var/www/yggdrasil
        ports:
            - 8090:80
        networks:
            - yggdrasil-frontend-network

    yggdrasil-frontend:
        container_name: yggdrasil-frontend
        image: node:latest
        volumes:
            - ./app:/app
        working_dir: /app
        command: "bash -c 'yarn && yarn run build'"
        networks:
            - yggdrasil-frontend-network
