version: "3.5"
networks:
    vue-app-network:
        name: vue-app-network
services:
    nginx:
        container_name: vue-app-nginx
        image: nginx:latest
        restart: always
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./app/dist:/var/www/vue-app
        ports:
            - 8090:80
        networks:
            - vue-app-network

    vue-app:
        container_name: vue-app
        image: node:latest
        volumes:
            - ./app:/app
        working_dir: /app
        command: "bash -c 'yarn && yarn run build'"
        networks:
            - vue-app-network
